name: Sync Repository Docs to Confluence

on:
  push:
    branches:
      - main  
    paths:
      - 'docs/**'  

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Codebase
        uses: actions/checkout@v4

      - name: Publish Markdown Docs to Confluence
        uses: markdown-confluence/publish-action@v5
        with:
          confluenceBaseUrl: 'https://vidushan145.atlassian.net' 
          confluenceParentId: '5472427'   
          atlassianUserName: 'vidurshan145@gmail.com'
          atlassianApiToken: ${{ secrets.ATLASSIAN_API_TOKEN }} 
          folderToPublish: '.'                              
          contentRoot: '.'